### ISSUE TITLE
Upgrade to grunt v0.4

### ISSUE THREAD

**Issue by samyakbhuta** [Ideame/grunt-css-urls#2]
Currently it is failing due to changes in properties available to a task.  `this.file` -> `this.files`. 

Some references,
- http://gruntjs.com/upgrading-from-0.3-to-0.4
- https://github.com/gruntjs/grunt/wiki/Inside-Tasks#wiki-this-target
- https://github.com/gruntjs/grunt/issues/606
- https://github.com/gruntjs/grunt-contrib-cssmin/commit/20f9247e63a9c6fa482bc99d4508a3789690b93e

**Comment by jpgarcia** [comment]
done, just published the v0.2.0 which is compatible with grunt 0.4.x

**Comment by samyakbhuta** [comment]
great +1
